{"time":"2024-10-10T20:27:15.7759858+05:30","level":"INFO","msg":"using version","core version":"0.18.3"}
{"time":"2024-10-10T20:27:15.7765309+05:30","level":"INFO","msg":"created symlink","path":"d:\\github\\HumanEmotions\\pytorch\\wandb\\wandb\\run-20241010_202706-196dm3ta\\logs\\debug-core.log"}
{"time":"2024-10-10T20:27:15.777075+05:30","level":"ERROR","msg":"dialing: google: could not find default credentials. See https://cloud.google.com/docs/authentication/external/set-up-adc for more information"}
{"time":"2024-10-10T20:27:15.8272252+05:30","level":"INFO","msg":"created new stream","id":"196dm3ta"}
{"time":"2024-10-10T20:27:15.8272252+05:30","level":"INFO","msg":"stream: started","id":"196dm3ta"}
{"time":"2024-10-10T20:27:15.827528+05:30","level":"INFO","msg":"writer: Do: started","stream_id":{"value":"196dm3ta"}}
{"time":"2024-10-10T20:27:15.827528+05:30","level":"INFO","msg":"sender: started","stream_id":{"value":"196dm3ta"}}
{"time":"2024-10-10T20:27:15.827528+05:30","level":"INFO","msg":"handler: started","stream_id":{"value":"196dm3ta"}}
{"time":"2024-10-10T20:27:16.6241003+05:30","level":"INFO","msg":"wandb-core","!BADKEY":null}
{"time":"2024-10-10T20:27:16.6246139+05:30","level":"INFO","msg":"Starting system monitor"}
{"time":"2024-10-10T22:30:45.1522441+05:30","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/ravikumarchavva-org/transformers-human-pose-estimation/196dm3ta/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2024-10-10T22:31:04.2875358+05:30","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 192.168.1.5:51064->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
