2024-10-10 23:12:34,816 INFO    MainThread:16784 [wandb_setup.py:_flush():79] Current SDK version is 0.18.3
2024-10-10 23:12:34,816 INFO    MainThread:16784 [wandb_setup.py:_flush():79] Configure stats pid to 16784
2024-10-10 23:12:34,817 INFO    MainThread:16784 [wandb_setup.py:_flush():79] Loading settings from C:\Users\chavv\.config\wandb\settings
2024-10-10 23:12:34,817 INFO    MainThread:16784 [wandb_setup.py:_flush():79] Loading settings from d:\github\HumanEmotions\pytorch\wandb\wandb\settings
2024-10-10 23:12:34,817 INFO    MainThread:16784 [wandb_setup.py:_flush():79] Loading settings from environment variables: {'api_key': '***REDACTED***'}
2024-10-10 23:12:34,817 INFO    MainThread:16784 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-10-10 23:12:34,817 INFO    MainThread:16784 [wandb_setup.py:_flush():79] Applying login settings: {'api_key': '***REDACTED***'}
2024-10-10 23:12:34,817 INFO    MainThread:16784 [wandb_setup.py:_flush():79] Applying login settings: {'api_key': '***REDACTED***'}
2024-10-10 23:12:34,817 INFO    MainThread:16784 [wandb_setup.py:_flush():79] Applying login settings: {}
2024-10-10 23:12:34,817 INFO    MainThread:16784 [wandb_init.py:_log_setup():532] Logging user logs to d:\github\HumanEmotions\pytorch\wandb\wandb\run-20241010_231234-mxflkfsx\logs\debug.log
2024-10-10 23:12:34,817 INFO    MainThread:16784 [wandb_init.py:_log_setup():533] Logging internal logs to d:\github\HumanEmotions\pytorch\wandb\wandb\run-20241010_231234-mxflkfsx\logs\debug-internal.log
2024-10-10 23:12:34,817 INFO    MainThread:16784 [wandb_init.py:init():617] calling init triggers
2024-10-10 23:12:34,818 INFO    MainThread:16784 [wandb_init.py:init():624] wandb.init called with sweep_config: {}
config: {'learning_rate': 1e-05, 'epochs': 30, 'batch_size': 1, 'image_size': 224, 'num_classes': 3}
2024-10-10 23:12:34,818 INFO    MainThread:16784 [wandb_init.py:init():642] re-initializing run, found existing run on stack: kc0o19kd
2024-10-10 23:12:34,820 INFO    MainThread:16784 [wandb_run.py:_finish():2164] finishing run ravikumarchavva-org/transformers-human-pose-estimation/kc0o19kd
2024-10-10 23:12:34,820 INFO    MainThread:16784 [jupyter.py:save_history():459] not saving jupyter history
2024-10-10 23:12:34,820 INFO    MainThread:16784 [jupyter.py:save_ipynb():387] not saving jupyter notebook
2024-10-10 23:12:34,820 INFO    MainThread:16784 [wandb_init.py:_jupyter_teardown():460] cleaning up jupyter logic
2024-10-10 23:12:34,820 INFO    MainThread:16784 [wandb_run.py:_atexit_cleanup():2428] got exitcode: 0
2024-10-10 23:12:34,821 INFO    MainThread:16784 [wandb_run.py:_restore():2410] restore
2024-10-10 23:12:34,821 INFO    MainThread:16784 [wandb_run.py:_restore():2416] restore done
2024-10-10 23:12:38,738 INFO    MainThread:16784 [wandb_run.py:_footer_history_summary_info():4049] rendering history
2024-10-10 23:12:38,738 INFO    MainThread:16784 [wandb_run.py:_footer_history_summary_info():4081] rendering summary
2024-10-10 23:12:38,744 INFO    MainThread:16784 [wandb_run.py:_footer_sync_info():4008] logging synced files
2024-10-10 23:12:39,331 INFO    MainThread:16784 [wandb_init.py:init():667] starting backend
2024-10-10 23:12:39,331 INFO    MainThread:16784 [wandb_init.py:init():671] sending inform_init request
2024-10-10 23:12:39,333 INFO    MainThread:16784 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=spawn, using: spawn
2024-10-10 23:12:39,333 INFO    MainThread:16784 [wandb_init.py:init():684] backend started and connected
2024-10-10 23:12:39,339 INFO    MainThread:16784 [wandb_run.py:_label_probe_notebook():1346] probe notebook
2024-10-10 23:12:39,339 INFO    MainThread:16784 [wandb_run.py:_label_probe_notebook():1356] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-10-10 23:12:39,339 INFO    MainThread:16784 [wandb_init.py:init():779] updated telemetry
2024-10-10 23:12:39,410 INFO    MainThread:16784 [wandb_init.py:init():812] communicating run to backend with 90.0 second timeout
2024-10-10 23:12:39,928 INFO    MainThread:16784 [wandb_init.py:init():863] starting run threads in backend
2024-10-10 23:12:40,102 INFO    MainThread:16784 [wandb_run.py:_console_start():2465] atexit reg
2024-10-10 23:12:40,103 INFO    MainThread:16784 [wandb_run.py:_redirect():2313] redirect: wrap_raw
2024-10-10 23:12:40,103 INFO    MainThread:16784 [wandb_run.py:_redirect():2378] Wrapping output streams.
2024-10-10 23:12:40,103 INFO    MainThread:16784 [wandb_run.py:_redirect():2403] Redirects installed.
2024-10-10 23:12:40,103 INFO    MainThread:16784 [wandb_init.py:init():907] run started, returning control to user process
